# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xatPrivat.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fxatPrivat.proto\"\"\n\x0e\x43onnectRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\"\n\x0f\x43onnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"9\n\x07Message\x12\x11\n\tfrom_user\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\nMessageAck\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\x05\x45mpty\x12\x10\n\x08username\x18\x01 \x01(\t2\xf9\x01\n\x0bPrivateChat\x12.\n\x07\x43onnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12&\n\x0bSendMessage\x12\x08.Message\x1a\x0b.MessageAck\"\x00\x12\'\n\x0fReceiveMessages\x12\x06.Empty\x1a\x08.Message\"\x00\x30\x01\x12\x36\n\x0fIsUserConnected\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x12\x31\n\nDisconnect\x12\x0f.ConnectRequest\x1a\x10.ConnectResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'xatPrivat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONNECTREQUEST']._serialized_start=19
  _globals['_CONNECTREQUEST']._serialized_end=53
  _globals['_CONNECTRESPONSE']._serialized_start=55
  _globals['_CONNECTRESPONSE']._serialized_end=89
  _globals['_MESSAGE']._serialized_start=91
  _globals['_MESSAGE']._serialized_end=148
  _globals['_MESSAGEACK']._serialized_start=150
  _globals['_MESSAGEACK']._serialized_end=179
  _globals['_EMPTY']._serialized_start=181
  _globals['_EMPTY']._serialized_end=206
  _globals['_PRIVATECHAT']._serialized_start=209
  _globals['_PRIVATECHAT']._serialized_end=458
# @@protoc_insertion_point(module_scope)
