master:
  ip: "localhost"
  port: 32770
  address: "localhost:50051"
slaves:
  - ip: "localhost"
    port: 32771
    address: "localhost:50052"
  - ip: "localhost"
    port: 32772
    address: "localhost:50053"
